apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: mongodb-secret
  namespace: purely
spec:
  tokenSecret:
    name: doppler-token
    namespace: purely
  managedSecret:
    name: mongodb-secret
  project: purely
  config: prd
  processors:
    - type: remap
      keys:
        MONGODB_USERNAME: mongo-root-username
        MONGODB_PASSWORD: mongo-root-password