apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: email-secret
  namespace: purely
spec:
  tokenSecret:
    name: doppler-token
    namespace: purely
  managedSecret:
    name: email-secret
  project: purely
  config: prd