apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: email-secret
  namespace: purely
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: email-secret
    creationPolicy: Owner
  data:
    - secretKey: SMTP_SERVER_URL
      remoteRef:
        key: SMTP_SERVER_URL
    - secretKey: SMTP_SERVER_PORT
      remoteRef:
        key: SMTP_SERVER_PORT
    - secretKey: EMAIL_USERNAME
      remoteRef:
        key: EMAIL_USERNAME
    - secretKey: EMAIL_PASSWORD
      remoteRef:
        key: EMAIL_PASSWORD