apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: purely
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: mongo-root-username
      remoteRef:
        key: MONGODB_USERNAME
    - secretKey: mongo-root-password
      remoteRef:
        key: MONGODB_PASSWORD