apiVersion: v1
kind: Secret
metadata:
  name: doppler-config
  namespace: external-secrets
type: Opaque
stringData:
  project: purely
  config: default
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler
spec:
  provider:
    doppler:
      config: doppler-config
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            key: dopplerToken
            namespace: external-secrets